[package]
name = "bubbles"
version = "0.1.0"
edition = "2021"

[dependencies]
adw = { version = "0.7.1", package = "libadwaita", features = ["v1_5"] }
async-channel = "2.3.1"
gtk = { version = "0.9.4", package = "gtk4", features = ["v4_16"] }
libc = "0.2.168"